#Importación de librerías

In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from lightgbm import LGBMClassifier
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split
from sklearn.metrics import accuracy_score
!pip install kaggle
!pip install optuna lightgbm

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.6.15)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)
Requirement already satisfied: optuna in /usr/local/lib/python3.11/dist-packages (4.4.0)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.11/dist-packages (4.5.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (1.16.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from optuna) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from lightgbm) (1.15.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)

In [52]:
import optuna

# Carga de los datos

In [7]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [8]:
!kaggle competitions download -c udea-ai-4-eng-20251-pruebas-saber-pro-colombia

Downloading udea-ai-4-eng-20251-pruebas-saber-pro-colombia.zip to /content
  0% 0.00/29.9M [00:00<?, ?B/s]
100% 29.9M/29.9M [00:00<00:00, 2.01GB/s]

In [9]:
!unzip -l udea-ai-4-eng-20251-pruebas-saber-pro-colombia

Archive:  udea-ai-4-eng-20251-pruebas-saber-pro-colombia.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  4716673  2025-03-25 16:54   submission_example.csv
 59185250  2025-03-25 16:54   test.csv
143732449  2025-03-25 16:54   train.csv
---------                     -------
207634372                     3 files

In [10]:
!unzip udea-ai-4-eng-20251-pruebas-saber-pro-colombia

Archive:  udea-ai-4-eng-20251-pruebas-saber-pro-colombia.zip
  inflating: submission_example.csv
  inflating: test.csv
  inflating: train.csv

In [11]:
!ls -lash *.csv

4.5M -rw-r--r-- 1 root root 4.5M Mar 25 16:54 submission_example.csv
 57M -rw-r--r-- 1 root root  57M Mar 25 16:54 test.csv
138M -rw-r--r-- 1 root root 138M Mar 25 16:54 train.csv

# Exploración

In [12]:
dtr = pd.read_csv('train.csv')

In [13]:
dtr.shape

(692500, 21)

In [14]:
dtr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692500 entries, 0 to 692499
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              692500 non-null  int64
 1   PERIODO                         692500 non-null  int64
 2   ESTU_PRGM_ACADEMICO             692500 non-null  object
 3   ESTU_PRGM_DEPARTAMENTO          692500 non-null  object
 4   ESTU_VALORMATRICULAUNIVERSIDAD  686213 non-null  object
 5   ESTU_HORASSEMANATRABAJA         661643 non-null  object
 6   FAMI_ESTRATOVIVIENDA            660363 non-null  object
 7   FAMI_TIENEINTERNET              665871 non-null  object
 8   FAMI_EDUCACIONPADRE             669322 non-null  object
 9   FAMI_TIENELAVADORA              652727 non-null  object
 10  FAMI_TIENEAUTOMOVIL             648877 non-null  object
 11  ESTU_PRIVADO_LIBERTAD           692500 non-null  object
 12  ESTU_PAGOMATRICULAPROPIO        686002 non-null  object
 13  FAMI_TIENECOMPUTADOR            654397 non-null  object
 14  FAMI_TIENEINTERNET.1            665871 non-null  object
 15  FAMI_EDUCACIONMADRE             668836 non-null  object
 16  RENDIMIENTO_GLOBAL              692500 non-null  object
 17  coef_1                          692500 non-null  float64
 18  coef_2                          692500 non-null  float64
 19  coef_3                          692500 non-null  float64
 20  coef_4                          692500 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 111.0+ MB

In [15]:
dtr.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

**Analizamos valores faltantes y observamos los datos de algunas variables**

In [16]:
for i in dtr.columns:
    print ("%20s"%i, np.sum(dtr[i].isna()))

                  ID 0
             PERIODO 0
 ESTU_PRGM_ACADEMICO 0
ESTU_PRGM_DEPARTAMENTO 0
ESTU_VALORMATRICULAUNIVERSIDAD 6287
ESTU_HORASSEMANATRABAJA 30857
FAMI_ESTRATOVIVIENDA 32137
  FAMI_TIENEINTERNET 26629
 FAMI_EDUCACIONPADRE 23178
  FAMI_TIENELAVADORA 39773
 FAMI_TIENEAUTOMOVIL 43623
ESTU_PRIVADO_LIBERTAD 0
ESTU_PAGOMATRICULAPROPIO 6498
FAMI_TIENECOMPUTADOR 38103
FAMI_TIENEINTERNET.1 26629
 FAMI_EDUCACIONMADRE 23664
  RENDIMIENTO_GLOBAL 0
              coef_1 0
              coef_2 0
              coef_3 0
              coef_4 0

In [17]:
dtr.ESTU_HORASSEMANATRABAJA.value_counts()

ESTU_HORASSEMANATRABAJA
Más de 30 horas        249352
0                      116550
Entre 11 y 20 horas    115857
Entre 21 y 30 horas     92693
Menos de 10 horas       87191
Name: count, dtype: int64

In [18]:
dtr.RENDIMIENTO_GLOBAL.value_counts()

RENDIMIENTO_GLOBAL
alto          175619
bajo          172987
medio-bajo    172275
medio-alto    171619
Name: count, dtype: int64

In [19]:
dtr.ESTU_PRIVADO_LIBERTAD.value_counts()

ESTU_PRIVADO_LIBERTAD
N    692466
S        34
Name: count, dtype: int64

# Preprocesado

In [20]:
dtr.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

In [21]:
for i in dtr.columns:
    print ("%20s"%i, np.sum(dtr[i].isna()))

                  ID 0
             PERIODO 0
 ESTU_PRGM_ACADEMICO 0
ESTU_PRGM_DEPARTAMENTO 0
ESTU_VALORMATRICULAUNIVERSIDAD 6287
ESTU_HORASSEMANATRABAJA 30857
FAMI_ESTRATOVIVIENDA 32137
  FAMI_TIENEINTERNET 26629
 FAMI_EDUCACIONPADRE 23178
  FAMI_TIENELAVADORA 39773
 FAMI_TIENEAUTOMOVIL 43623
ESTU_PRIVADO_LIBERTAD 0
ESTU_PAGOMATRICULAPROPIO 6498
FAMI_TIENECOMPUTADOR 38103
FAMI_TIENEINTERNET.1 26629
 FAMI_EDUCACIONMADRE 23664
  RENDIMIENTO_GLOBAL 0
              coef_1 0
              coef_2 0
              coef_3 0
              coef_4 0

In [22]:
dtr.FAMI_EDUCACIONMADRE.value_counts()

FAMI_EDUCACIONMADRE
Secundaria (Bachillerato) completa      141744
Primaria incompleta                      99420
Técnica o tecnológica completa           89542
Educación profesional completa           85326
Secundaria (Bachillerato) incompleta     81012
Primaria completa                        56125
Postgrado                                46246
Técnica o tecnológica incompleta         27533
Educación profesional incompleta         22470
Ninguno                                  14483
No sabe                                   3017
No Aplica                                 1918
Name: count, dtype: int64

In [23]:
dtr.FAMI_ESTRATOVIVIENDA.value_counts()

FAMI_ESTRATOVIVIENDA
Estrato 2      232671
Estrato 3      210685
Estrato 1      111991
Estrato 4       65514
Estrato 5       23608
Estrato 6       12605
Sin Estrato      3289
Name: count, dtype: int64

In [24]:
dtr.ESTU_HORASSEMANATRABAJA.value_counts()

ESTU_HORASSEMANATRABAJA
Más de 30 horas        249352
0                      116550
Entre 11 y 20 horas    115857
Entre 21 y 30 horas     92693
Menos de 10 horas       87191
Name: count, dtype: int64

In [25]:
dtr.ESTU_VALORMATRICULAUNIVERSIDAD.value_counts()

ESTU_VALORMATRICULAUNIVERSIDAD
Entre 1 millón y menos de 2.5 millones      204048
Entre 2.5 millones y menos de 4 millones    127430
Menos de 500 mil                             80263
Entre 500 mil y menos de 1 millón            78704
Entre 4 millones y menos de 5.5 millones     69736
Más de 7 millones                            68014
Entre 5.5 millones y menos de 7 millones     38490
No pagó matrícula                            19528
Name: count, dtype: int64

## Función de preprocesado

Se eliminan columnas poco relevantes y se usa la codificación ordinal para columnas de tipo objeto

In [26]:
def preprocesar_datos(df, es_entrenamiento=True, mapeo_target=None, encoder=None):
  df = df.copy()

  columnas_a_eliminar = [
        'FAMI_TIENEINTERNET.1',
        'ESTU_PRIVADO_LIBERTAD',
        'FAMI_TIENELAVADORA',
        'FAMI_TIENEAUTOMOVIL',
        'PERIODO'
  ]

  for col in columnas_a_eliminar:
      if col in df.columns:
          del df[col]

  # Imputar valores nulos con moda
  for col in df.select_dtypes(include='object').columns:
      df[col].fillna(df[col].mode()[0], inplace=True)

  # Imputar valores nulos numéricos si es necesario
  for col in df.select_dtypes(include=['float64', 'int64']).columns:
      df[col].fillna(df[col].median(), inplace=True)

  # Codificación ordinal para educación
  educacion_orden = {
      'Ninguno': 0,
      'Primaria incompleta': 1,
      'Primaria completa': 2,
      'Secundaria (Bachillerato) incompleta': 3,
      'Secundaria (Bachillerato) completa': 4,
      'Técnica o tecnológica incompleta': 5,
      'Técnica o tecnológica completa': 6,
      'Educación profesional incompleta': 7,
      'Educación profesional completa': 8,
      'Postgrado': 9,
      'No sabe': -1,
      'No aplica': -2
  }

  for col in ['FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE']:
    if col in df.columns:
        df[col] = df[col].map(educacion_orden)

  # Codificación ordinal para estrato
  estrato_map = {
      'Sin Estrato': 0,
      'Estrato 1': 1,
      'Estrato 2': 2,
      'Estrato 3': 3,
      'Estrato 4': 4,
      'Estrato 5': 5,
      'Estrato 6': 6
  }
  if 'FAMI_ESTRATOVIVIENDA' in df.columns:
    df['FAMI_ESTRATOVIVIENDA'] = df['FAMI_ESTRATOVIVIENDA'].map(estrato_map)

  # Codificación ordinal para horas de trabajo
  horas_map = {
      '0': 0,
      'Menos de 10 horas': 1,
      'Entre 11 y 20 horas': 2,
      'Entre 21 y 30 horas': 3,
      'Más de 30 horas': 4
  }
  if 'ESTU_HORASSEMANATRABAJA' in df.columns:
    df['ESTU_HORASSEMANATRABAJA'] = df['ESTU_HORASSEMANATRABAJA'].map(horas_map)

  # Codificación ordinal para matrícula
  matricula_map = {
      'No pagó matrícula': 0,
      'Menos de 500 mil': 1,
      'Entre 500 mil y menos de 1 millón': 2,
      'Entre 1 millón y menos de 2.5 millones': 3,
      'Entre 2.5 millones y menos de 4 millones': 4,
      'Entre 4 millones y menos de 5.5 millones': 5,
      'Entre 5.5 millones y menos de 7 millones': 6,
      'Más de 7 millones': 7
  }
  if 'ESTU_VALORMATRICULAUNIVERSIDAD' in df.columns:
    df['ESTU_VALORMATRICULAUNIVERSIDAD'] = df['ESTU_VALORMATRICULAUNIVERSIDAD'].map(matricula_map)

  # Codificación binaria para Si/No
  bin_cols = [col for col in df.columns if df[col].nunique() == 2 and df[col].dtype == 'object']
  for col in bin_cols:
    df[col] = df[col].map({'Si': 1, 'No': 0, 'S': 1, 'N': 0})

  # Codificación ordinal para el resto de categóricas usando OrdinalEncoder
  categ_cols = df.select_dtypes(include='object').columns.tolist()
  if 'RENDIMIENTO_GLOBAL' in categ_cols:
    categ_cols.remove('RENDIMIENTO_GLOBAL')
  if es_entrenamiento:
    encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    df[categ_cols] = encoder.fit_transform(df[categ_cols])
  else:
    df[categ_cols] = encoder.transform(df[categ_cols])

  # Codificar la variable objetivo si es entrenamiento
  if es_entrenamiento and 'RENDIMIENTO_GLOBAL' in df.columns:
    mapeo_target = {'bajo': 0, 'medio-bajo': 1, 'medio-alto': 2, 'alto': 3}
    df['RENDIMIENTO_GLOBAL'] = df['RENDIMIENTO_GLOBAL'].map(mapeo_target)

  return df, mapeo_target, encoder

In [27]:
dtr_proc, mapeo_target, encoder = preprocesar_datos(dtr, es_entrenamiento=True)

/tmp/ipython-input-26-2469281481.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipython-input-26-2469281481.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

## Separación

In [28]:
X = dtr_proc.drop('RENDIMIENTO_GLOBAL', axis=1)
y = dtr_proc['RENDIMIENTO_GLOBAL']

## Carga y Preprocesado del archivo test

In [29]:
dts = pd.read_csv('test.csv')

In [30]:
dts.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,FAMI_TIENEAUTOMOVIL,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,coef_1,coef_2,coef_3,coef_4
0,550236,20183,TRABAJO SOCIAL,BOLIVAR,Menos de 500 mil,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica completa,Si,No,N,Si,Si,Si,Primaria completa,0.328,0.219,0.317,0.247
1,98545,20203,ADMINISTRACION COMERCIAL Y DE MERCADEO,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Si,No,N,No,Si,Si,Técnica o tecnológica completa,0.227,0.283,0.296,0.324
2,499179,20212,INGENIERIA MECATRONICA,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,0,Estrato 3,Si,Secundaria (Bachillerato) incompleta,Si,No,N,No,Si,Si,Secundaria (Bachillerato) completa,0.285,0.228,0.294,0.247
3,782980,20195,CONTADURIA PUBLICA,SUCRE,Entre 1 millón y menos de 2.5 millones,Entre 21 y 30 horas,Estrato 1,No,Primaria incompleta,Si,No,N,No,No,No,Primaria incompleta,0.160,0.408,0.217,0.294
4,785185,20212,ADMINISTRACION DE EMPRESAS,ATLANTICO,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Si,No,N,No,Si,Si,Secundaria (Bachillerato) completa,0.209,0.283,0.306,0.286

Se utiliza la misma función con los parámetros que guardamos cuando la aplicamos en el archivo train

In [31]:
dts_proc, _, _ = preprocesar_datos(dts, es_entrenamiento=False, mapeo_target=mapeo_target, encoder=encoder)

/tmp/ipython-input-26-2469281481.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipython-input-26-2469281481.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [32]:
X_test = dts_proc.drop(columns=['ID'])
X_test = X_test.reindex(columns=X.columns, fill_value=0)

In [33]:
X_test.head()

,ID,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_EDUCACIONMADRE,coef_1,coef_2,coef_3,coef_4
0,0,943.0,5.0,1,1,3,1,6.0,1,1,2.0,0.328,0.219,0.317,0.247
1,0,12.0,1.0,4,3,2,1,4.0,0,1,6.0,0.227,0.283,0.296,0.324
2,0,456.0,4.0,3,0,3,1,3.0,0,1,4.0,0.285,0.228,0.294,0.247
3,0,229.0,27.0,3,3,1,0,1.0,0,0,1.0,0.160,0.408,0.217,0.294
4,0,14.0,3.0,4,2,2,1,4.0,0,1,4.0,0.209,0.283,0.306,0.286

# Solución final

## Optuna y validación cruzada

Se utiliza una función de optimización con optuna para identificar los parámetros más adecuados para el modelo escogido

In [62]:
# Función de optimización
def objective(trial):
  params = {
      'n_estimators': trial.suggest_int('n_estimators', 100, 300),
      'max_depth': trial.suggest_int('max_depth', 4, 10),
      'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2),
      'num_leaves': trial.suggest_int('num_leaves', 20, 100),
      'min_child_samples': trial.suggest_int('min_child_samples', 10, 100),
      'subsample': trial.suggest_float('subsample', 0.5, 1.0),
      'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
      'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
      'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0),
      'random_state': 42,
      'objective': 'multiclass',
      'num_class': 4
  }
  pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("clf", LGBMClassifier(**params))
    ])
  cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
  score = cross_val_score(pipeline, X, y, cv=cv, scoring='accuracy', n_jobs=-1)
  return score.mean()

# Ejecutar Optimización
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30)

print("Mejores parámetros encontrados:")
print(study.best_params)

[I 2025-07-04 00:58:52,973] A new study created in memory with name: no-name-da3b8d99-4115-4783-9fad-4dfcbdfb7596
[I 2025-07-04 01:01:58,275] Trial 0 finished with value: 0.41760288665372663 and parameters: {'n_estimators': 297, 'max_depth': 6, 'learning_rate': 0.01446815453513954, 'num_leaves': 69, 'min_child_samples': 15, 'subsample': 0.9668224944974702, 'colsample_bytree': 0.6594232445922275, 'reg_alpha': 0.5557628565633576, 'reg_lambda': 0.5839857030943416}. Best is trial 0 with value: 0.41760288665372663.
[I 2025-07-04 01:03:41,456] Trial 1 finished with value: 0.4249256312890306 and parameters: {'n_estimators': 209, 'max_depth': 5, 'learning_rate': 0.06515989871683567, 'num_leaves': 44, 'min_child_samples': 71, 'subsample': 0.5859123504101675, 'colsample_bytree': 0.8587308134215667, 'reg_alpha': 0.3445703318656844, 'reg_lambda': 0.019778129842616066}. Best is trial 1 with value: 0.4249256312890306.
[I 2025-07-04 01:06:06,156] Trial 2 finished with value: 0.42980360904035836 and parameters: {'n_estimators': 226, 'max_depth': 8, 'learning_rate': 0.05624548942616445, 'num_leaves': 89, 'min_child_samples': 56, 'subsample': 0.5211041851297549, 'colsample_bytree': 0.536346930881186, 'reg_alpha': 0.5863284180603219, 'reg_lambda': 0.2490856435032217}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:09:08,051] Trial 3 finished with value: 0.4160101065971577 and parameters: {'n_estimators': 236, 'max_depth': 8, 'learning_rate': 0.011097087936905897, 'num_leaves': 67, 'min_child_samples': 78, 'subsample': 0.9834313487134214, 'colsample_bytree': 0.790366634968507, 'reg_alpha': 0.07029222469868135, 'reg_lambda': 0.22656158599756604}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:10:41,551] Trial 4 finished with value: 0.4280086622265009 and parameters: {'n_estimators': 232, 'max_depth': 4, 'learning_rate': 0.19958982167313943, 'num_leaves': 26, 'min_child_samples': 60, 'subsample': 0.8917109301317819, 'colsample_bytree': 0.892981937490259, 'reg_alpha': 0.9549440540974057, 'reg_lambda': 0.19272929734266575}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:12:18,360] Trial 5 finished with value: 0.42839277844852974 and parameters: {'n_estimators': 228, 'max_depth': 6, 'learning_rate': 0.12646920700675024, 'num_leaves': 26, 'min_child_samples': 20, 'subsample': 0.886190588185332, 'colsample_bytree': 0.6705071311159021, 'reg_alpha': 0.011387489290409891, 'reg_lambda': 0.13020392088771582}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:13:49,154] Trial 6 finished with value: 0.42549025207335206 and parameters: {'n_estimators': 214, 'max_depth': 4, 'learning_rate': 0.11488407628828548, 'num_leaves': 25, 'min_child_samples': 81, 'subsample': 0.5290925118891084, 'colsample_bytree': 0.6518607809018033, 'reg_alpha': 0.041755571475481146, 'reg_lambda': 0.9175670635316395}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:15:53,783] Trial 7 finished with value: 0.4293371832686139 and parameters: {'n_estimators': 246, 'max_depth': 10, 'learning_rate': 0.06303192555094278, 'num_leaves': 41, 'min_child_samples': 16, 'subsample': 0.7674559226246676, 'colsample_bytree': 0.5714455121334941, 'reg_alpha': 0.35065952965075575, 'reg_lambda': 0.3000309412810097}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:18:17,705] Trial 8 finished with value: 0.4283379045166397 and parameters: {'n_estimators': 283, 'max_depth': 5, 'learning_rate': 0.08559044517980124, 'num_leaves': 93, 'min_child_samples': 58, 'subsample': 0.7062888270694005, 'colsample_bytree': 0.785114896553351, 'reg_alpha': 0.5149018144492906, 'reg_lambda': 0.2598208226427594}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:20:03,238] Trial 9 finished with value: 0.4291653421655101 and parameters: {'n_estimators': 280, 'max_depth': 7, 'learning_rate': 0.19541826430029977, 'num_leaves': 22, 'min_child_samples': 56, 'subsample': 0.6918708533075735, 'colsample_bytree': 0.7253274208836624, 'reg_alpha': 0.6032687067865397, 'reg_lambda': 0.013387550809764504}. Best is trial 2 with value: 0.42980360904035836.
[I 2025-07-04 01:21:34,970] Trial 10 finished with value: 0.4302180495277898 and parameters: {'n_estimators': 155, 'max_depth': 9, 'learning_rate': 0.14300624279819613, 'num_leaves': 99, 'min_child_samples': 39, 'subsample': 0.6091953432243273, 'colsample_bytree': 0.5135608471694437, 'reg_alpha': 0.7635793974003884, 'reg_lambda': 0.520779696433987}. Best is trial 10 with value: 0.4302180495277898.
[I 2025-07-04 01:23:02,609] Trial 11 finished with value: 0.4300635374450035 and parameters: {'n_estimators': 154, 'max_depth': 9, 'learning_rate': 0.16591263784439822, 'num_leaves': 96, 'min_child_samples': 35, 'subsample': 0.5012010947858434, 'colsample_bytree': 0.5249757963907931, 'reg_alpha': 0.8326266078743445, 'reg_lambda': 0.5506896936129192}. Best is trial 10 with value: 0.4302180495277898.
[I 2025-07-04 01:24:26,445] Trial 12 finished with value: 0.42905126196532556 and parameters: {'n_estimators': 144, 'max_depth': 10, 'learning_rate': 0.1548524943801134, 'num_leaves': 100, 'min_child_samples': 35, 'subsample': 0.6177155722908796, 'colsample_bytree': 0.9887108295881906, 'reg_alpha': 0.9326680933484385, 'reg_lambda': 0.5578015958290882}. Best is trial 10 with value: 0.4302180495277898.
[I 2025-07-04 01:25:46,825] Trial 13 finished with value: 0.43020649697060825 and parameters: {'n_estimators': 148, 'max_depth': 9, 'learning_rate': 0.15721721955529086, 'num_leaves': 81, 'min_child_samples': 38, 'subsample': 0.6226332375761505, 'colsample_bytree': 0.5380120599941305, 'reg_alpha': 0.7679579233884807, 'reg_lambda': 0.7483858770534008}. Best is trial 10 with value: 0.4302180495277898.
[I 2025-07-04 01:26:53,073] Trial 14 finished with value: 0.4303032487385179 and parameters: {'n_estimators': 109, 'max_depth': 9, 'learning_rate': 0.14408330425103535, 'num_leaves': 80, 'min_child_samples': 37, 'subsample': 0.6331258533758626, 'colsample_bytree': 0.5838940137971592, 'reg_alpha': 0.772993874852836, 'reg_lambda': 0.7902105006061393}. Best is trial 14 with value: 0.4303032487385179.
[I 2025-07-04 01:27:57,590] Trial 15 finished with value: 0.43009241838441364 and parameters: {'n_estimators': 103, 'max_depth': 9, 'learning_rate': 0.14242130223673946, 'num_leaves': 81, 'min_child_samples': 44, 'subsample': 0.7407699498575856, 'colsample_bytree': 0.6041221173693623, 'reg_alpha': 0.7365128054233343, 'reg_lambda': 0.7414057120088196}. Best is trial 14 with value: 0.4303032487385179.
[I 2025-07-04 01:29:00,077] Trial 16 finished with value: 0.43017906066464745 and parameters: {'n_estimators': 103, 'max_depth': 8, 'learning_rate': 0.17649632373951815, 'num_leaves': 79, 'min_child_samples': 25, 'subsample': 0.6671357316644708, 'colsample_bytree': 0.6153600613178503, 'reg_alpha': 0.693001348915156, 'reg_lambda': 0.9407038721511942}. Best is trial 14 with value: 0.4303032487385179.
[I 2025-07-04 01:30:31,084] Trial 17 finished with value: 0.42992779674513804 and parameters: {'n_estimators': 170, 'max_depth': 10, 'learning_rate': 0.09731695974404506, 'num_leaves': 53, 'min_child_samples': 46, 'subsample': 0.8135650041655282, 'colsample_bytree': 0.5134597839893595, 'reg_alpha': 0.3948794058629064, 'reg_lambda': 0.38151833326525897}. Best is trial 14 with value: 0.4303032487385179.
[I 2025-07-04 01:32:00,935] Trial 18 finished with value: 0.42917256188582514 and parameters: {'n_estimators': 127, 'max_depth': 7, 'learning_rate': 0.1328885456980649, 'num_leaves': 87, 'min_child_samples': 99, 'subsample': 0.5742382955866352, 'colsample_bytree': 0.7232448988352403, 'reg_alpha': 0.8582386786877724, 'reg_lambda': 0.7951813533881027}. Best is trial 14 with value: 0.4303032487385179.
[I 2025-07-04 01:33:40,491] Trial 19 finished with value: 0.4303884462163965 and parameters: {'n_estimators': 179, 'max_depth': 9, 'learning_rate': 0.10689502352138926, 'num_leaves': 72, 'min_child_samples': 27, 'subsample': 0.6472313481983613, 'colsample_bytree': 0.5776077958356138, 'reg_alpha': 0.6636981141208012, 'reg_lambda': 0.4021319499475967}. Best is trial 19 with value: 0.4303884462163965.
[I 2025-07-04 01:35:22,656] Trial 20 finished with value: 0.4309833923108348 and parameters: {'n_estimators': 186, 'max_depth': 8, 'learning_rate': 0.10896857526914323, 'num_leaves': 68, 'min_child_samples': 28, 'subsample': 0.6567784259420337, 'colsample_bytree': 0.6005678140740965, 'reg_alpha': 0.20510991181962335, 'reg_lambda': 0.39092464329453414}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:37:06,801] Trial 21 finished with value: 0.42992346442124507 and parameters: {'n_estimators': 185, 'max_depth': 8, 'learning_rate': 0.10146012820253837, 'num_leaves': 71, 'min_child_samples': 25, 'subsample': 0.6552656094678838, 'colsample_bytree': 0.5908062066641373, 'reg_alpha': 0.19783750899502575, 'reg_lambda': 0.40946881650924855}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:38:41,484] Trial 22 finished with value: 0.4304303238960217 and parameters: {'n_estimators': 193, 'max_depth': 9, 'learning_rate': 0.11906864814244546, 'num_leaves': 60, 'min_child_samples': 10, 'subsample': 0.7389729154021273, 'colsample_bytree': 0.6326447194310112, 'reg_alpha': 0.23052690267458806, 'reg_lambda': 0.4133551761425074}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:40:26,380] Trial 23 finished with value: 0.43000577419616864 and parameters: {'n_estimators': 188, 'max_depth': 8, 'learning_rate': 0.0821817237226344, 'num_leaves': 58, 'min_child_samples': 11, 'subsample': 0.7949181945091278, 'colsample_bytree': 0.6921475420626257, 'reg_alpha': 0.19463472584614747, 'reg_lambda': 0.42500736730665745}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:42:00,794] Trial 24 finished with value: 0.4305978338638298 and parameters: {'n_estimators': 188, 'max_depth': 10, 'learning_rate': 0.11409455918740984, 'num_leaves': 62, 'min_child_samples': 26, 'subsample': 0.7395627648046579, 'colsample_bytree': 0.6328380003947347, 'reg_alpha': 0.23552457585991626, 'reg_lambda': 0.3461083606600381}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:43:34,584] Trial 25 finished with value: 0.43020794164159226 and parameters: {'n_estimators': 199, 'max_depth': 10, 'learning_rate': 0.12164488767472482, 'num_leaves': 49, 'min_child_samples': 28, 'subsample': 0.7275501543860842, 'colsample_bytree': 0.6299729740427048, 'reg_alpha': 0.21409144818869846, 'reg_lambda': 0.6209641797413042}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:45:41,095] Trial 26 finished with value: 0.43052563022348705 and parameters: {'n_estimators': 254, 'max_depth': 10, 'learning_rate': 0.08328897842479838, 'num_leaves': 62, 'min_child_samples': 19, 'subsample': 0.8352664926288418, 'colsample_bytree': 0.6986898268393007, 'reg_alpha': 0.1284961027810047, 'reg_lambda': 0.3311602283301669}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:48:30,881] Trial 27 finished with value: 0.4295667861629573 and parameters: {'n_estimators': 258, 'max_depth': 10, 'learning_rate': 0.036900328649656984, 'num_leaves': 64, 'min_child_samples': 19, 'subsample': 0.8575629951149473, 'colsample_bytree': 0.764736668005872, 'reg_alpha': 0.11946609335739432, 'reg_lambda': 0.3370030088569419}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:49:59,561] Trial 28 finished with value: 0.4290945839343327 and parameters: {'n_estimators': 167, 'max_depth': 10, 'learning_rate': 0.08494004970423458, 'num_leaves': 35, 'min_child_samples': 49, 'subsample': 0.7958726809720422, 'colsample_bytree': 0.7073614167273122, 'reg_alpha': 0.4358312406497623, 'reg_lambda': 0.1507976016215381}. Best is trial 20 with value: 0.4309833923108348.
[I 2025-07-04 01:52:32,781] Trial 29 finished with value: 0.4262628146392699 and parameters: {'n_estimators': 267, 'max_depth': 6, 'learning_rate': 0.03942653971782352, 'num_leaves': 53, 'min_child_samples': 30, 'subsample': 0.8394533356257432, 'colsample_bytree': 0.6759324019691996, 'reg_alpha': 0.12195080938069733, 'reg_lambda': 0.4832269925020737}. Best is trial 20 with value: 0.4309833923108348.

Mejores parámetros encontrados:
{'n_estimators': 186, 'max_depth': 8, 'learning_rate': 0.10896857526914323, 'num_leaves': 68, 'min_child_samples': 28, 'subsample': 0.6567784259420337, 'colsample_bytree': 0.6005678140740965, 'reg_alpha': 0.20510991181962335, 'reg_lambda': 0.39092464329453414}

## Entrenar modelo y realizar predicciones

In [63]:
best_pipeline = Pipeline([
  ("imputer", SimpleImputer(strategy="most_frequent")),
  ("clf", LGBMClassifier(
      **study.best_params,
      objective='multiclass',
      num_class=4,
      random_state=42
  ))
])

# Entrenar pipeline con TODO el conjunto de entrenamiento
best_pipeline.fit(X, y)

# Predecir
y_preds = best_pipeline.predict(X_test)

# Revertir codificación
reverse_map = {v: k for k, v in mapeo_target.items()}
y_preds_labels = pd.Series(y_preds).map(reverse_map)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025882 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1464
[LightGBM] [Info] Number of data points in the train set: 692500, number of used features: 15
[LightGBM] [Info] Start training from score -1.387092
[LightGBM] [Info] Start training from score -1.391216
[LightGBM] [Info] Start training from score -1.395031
[LightGBM] [Info] Start training from score -1.371991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

## Generar archivo de solución para Kaggle

In [64]:
submission = pd.DataFrame({
    'ID': dts['ID'],
    'RENDIMIENTO_GLOBAL': y_preds_labels
})
submission.head()

       ID RENDIMIENTO_GLOBAL
0  550236         medio-bajo
1   98545         medio-bajo
2  499179               alto
3  782980               bajo
4  785185               bajo

In [65]:
submission.to_csv('submission8.csv', index=False)

In [66]:
!head submission8.csv

ID,RENDIMIENTO_GLOBAL
550236,medio-bajo
98545,medio-bajo
499179,alto
782980,bajo
785185,bajo
58495,bajo
705444,alto
557548,alto
519909,bajo