#Importación de librerías

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split
!pip install kaggle
!pip install optuna

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.6.15)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)
Collecting optuna
  Downloading optuna-4.4.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.16.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)
Downloading optuna-4.4.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.9/395.9 kB 31.8 MB/s eta 0:00:00
Downloading alembic-1.16.2-py3-none-any.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.7/242.7 kB 23.6 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.16.2 colorlog-6.9.0 optuna-4.4.0

In [2]:
import optuna

# Carga de los datos

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle competitions download -c udea-ai-4-eng-20251-pruebas-saber-pro-colombia

Downloading udea-ai-4-eng-20251-pruebas-saber-pro-colombia.zip to /content
  0% 0.00/29.9M [00:00<?, ?B/s]
100% 29.9M/29.9M [00:00<00:00, 1.14GB/s]

In [5]:
!unzip -l udea-ai-4-eng-20251-pruebas-saber-pro-colombia

Archive:  udea-ai-4-eng-20251-pruebas-saber-pro-colombia.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  4716673  2025-03-25 16:54   submission_example.csv
 59185250  2025-03-25 16:54   test.csv
143732449  2025-03-25 16:54   train.csv
---------                     -------
207634372                     3 files

In [6]:
!unzip udea-ai-4-eng-20251-pruebas-saber-pro-colombia

Archive:  udea-ai-4-eng-20251-pruebas-saber-pro-colombia.zip
  inflating: submission_example.csv
  inflating: test.csv
  inflating: train.csv

In [7]:
!ls -lash *.csv

4.5M -rw-r--r-- 1 root root 4.5M Mar 25 16:54 submission_example.csv
 57M -rw-r--r-- 1 root root  57M Mar 25 16:54 test.csv
138M -rw-r--r-- 1 root root 138M Mar 25 16:54 train.csv

# Exploración

In [8]:
dtr = pd.read_csv('train.csv')

In [9]:
dtr.shape

(692500, 21)

In [10]:
dtr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692500 entries, 0 to 692499
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              692500 non-null  int64
 1   PERIODO                         692500 non-null  int64
 2   ESTU_PRGM_ACADEMICO             692500 non-null  object
 3   ESTU_PRGM_DEPARTAMENTO          692500 non-null  object
 4   ESTU_VALORMATRICULAUNIVERSIDAD  686213 non-null  object
 5   ESTU_HORASSEMANATRABAJA         661643 non-null  object
 6   FAMI_ESTRATOVIVIENDA            660363 non-null  object
 7   FAMI_TIENEINTERNET              665871 non-null  object
 8   FAMI_EDUCACIONPADRE             669322 non-null  object
 9   FAMI_TIENELAVADORA              652727 non-null  object
 10  FAMI_TIENEAUTOMOVIL             648877 non-null  object
 11  ESTU_PRIVADO_LIBERTAD           692500 non-null  object
 12  ESTU_PAGOMATRICULAPROPIO        686002 non-null  object
 13  FAMI_TIENECOMPUTADOR            654397 non-null  object
 14  FAMI_TIENEINTERNET.1            665871 non-null  object
 15  FAMI_EDUCACIONMADRE             668836 non-null  object
 16  RENDIMIENTO_GLOBAL              692500 non-null  object
 17  coef_1                          692500 non-null  float64
 18  coef_2                          692500 non-null  float64
 19  coef_3                          692500 non-null  float64
 20  coef_4                          692500 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 111.0+ MB

In [11]:
dtr.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

In [12]:
for i in dtr.columns:
    print ("%20s"%i, np.sum(dtr[i].isna()))

                  ID 0
             PERIODO 0
 ESTU_PRGM_ACADEMICO 0
ESTU_PRGM_DEPARTAMENTO 0
ESTU_VALORMATRICULAUNIVERSIDAD 6287
ESTU_HORASSEMANATRABAJA 30857
FAMI_ESTRATOVIVIENDA 32137
  FAMI_TIENEINTERNET 26629
 FAMI_EDUCACIONPADRE 23178
  FAMI_TIENELAVADORA 39773
 FAMI_TIENEAUTOMOVIL 43623
ESTU_PRIVADO_LIBERTAD 0
ESTU_PAGOMATRICULAPROPIO 6498
FAMI_TIENECOMPUTADOR 38103
FAMI_TIENEINTERNET.1 26629
 FAMI_EDUCACIONMADRE 23664
  RENDIMIENTO_GLOBAL 0
              coef_1 0
              coef_2 0
              coef_3 0
              coef_4 0

In [13]:
dtr.ESTU_HORASSEMANATRABAJA.value_counts()

ESTU_HORASSEMANATRABAJA
Más de 30 horas        249352
0                      116550
Entre 11 y 20 horas    115857
Entre 21 y 30 horas     92693
Menos de 10 horas       87191
Name: count, dtype: int64

In [14]:
dtr.RENDIMIENTO_GLOBAL.value_counts()

RENDIMIENTO_GLOBAL
alto          175619
bajo          172987
medio-bajo    172275
medio-alto    171619
Name: count, dtype: int64

In [15]:
dtr.ESTU_PRIVADO_LIBERTAD.value_counts()

ESTU_PRIVADO_LIBERTAD
N    692466
S        34
Name: count, dtype: int64

# Preprocesado

In [16]:
dtr.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

**Analizamos valores faltantes y observamos los datos de algunas variables**

In [17]:
for i in dtr.columns:
    print ("%20s"%i, np.sum(dtr[i].isna()))

                  ID 0
             PERIODO 0
 ESTU_PRGM_ACADEMICO 0
ESTU_PRGM_DEPARTAMENTO 0
ESTU_VALORMATRICULAUNIVERSIDAD 6287
ESTU_HORASSEMANATRABAJA 30857
FAMI_ESTRATOVIVIENDA 32137
  FAMI_TIENEINTERNET 26629
 FAMI_EDUCACIONPADRE 23178
  FAMI_TIENELAVADORA 39773
 FAMI_TIENEAUTOMOVIL 43623
ESTU_PRIVADO_LIBERTAD 0
ESTU_PAGOMATRICULAPROPIO 6498
FAMI_TIENECOMPUTADOR 38103
FAMI_TIENEINTERNET.1 26629
 FAMI_EDUCACIONMADRE 23664
  RENDIMIENTO_GLOBAL 0
              coef_1 0
              coef_2 0
              coef_3 0
              coef_4 0

In [18]:
dtr.FAMI_EDUCACIONMADRE.value_counts()

FAMI_EDUCACIONMADRE
Secundaria (Bachillerato) completa      141744
Primaria incompleta                      99420
Técnica o tecnológica completa           89542
Educación profesional completa           85326
Secundaria (Bachillerato) incompleta     81012
Primaria completa                        56125
Postgrado                                46246
Técnica o tecnológica incompleta         27533
Educación profesional incompleta         22470
Ninguno                                  14483
No sabe                                   3017
No Aplica                                 1918
Name: count, dtype: int64

In [19]:
dtr.FAMI_ESTRATOVIVIENDA.value_counts()

FAMI_ESTRATOVIVIENDA
Estrato 2      232671
Estrato 3      210685
Estrato 1      111991
Estrato 4       65514
Estrato 5       23608
Estrato 6       12605
Sin Estrato      3289
Name: count, dtype: int64

In [20]:
dtr.ESTU_HORASSEMANATRABAJA.value_counts()

ESTU_HORASSEMANATRABAJA
Más de 30 horas        249352
0                      116550
Entre 11 y 20 horas    115857
Entre 21 y 30 horas     92693
Menos de 10 horas       87191
Name: count, dtype: int64

In [21]:
dtr.ESTU_VALORMATRICULAUNIVERSIDAD.value_counts()

ESTU_VALORMATRICULAUNIVERSIDAD
Entre 1 millón y menos de 2.5 millones      204048
Entre 2.5 millones y menos de 4 millones    127430
Menos de 500 mil                             80263
Entre 500 mil y menos de 1 millón            78704
Entre 4 millones y menos de 5.5 millones     69736
Más de 7 millones                            68014
Entre 5.5 millones y menos de 7 millones     38490
No pagó matrícula                            19528
Name: count, dtype: int64

## Función de preprocesado

Se eliminan columnas poco relevantes y se usa la codificación ordinal para columnas de tipo objeto

In [22]:
def preprocesar_datos(df, es_entrenamiento=True, mapeo_target=None, encoder=None):
  df = df.copy()

  columnas_a_eliminar = [
        'FAMI_TIENEINTERNET.1',
        'ESTU_PRIVADO_LIBERTAD',
        'FAMI_TIENELAVADORA',
        'FAMI_TIENEAUTOMOVIL',
        'PERIODO'
  ]

  for col in columnas_a_eliminar:
      if col in df.columns:
          del df[col]

  # Imputar valores nulos con moda
  for col in df.select_dtypes(include='object').columns:
      df[col].fillna(df[col].mode()[0], inplace=True)

  # Imputar valores nulos numéricos si es necesario
  for col in df.select_dtypes(include=['float64', 'int64']).columns:
      df[col].fillna(df[col].median(), inplace=True)

  # Codificación ordinal para educación
  educacion_orden = {
      'Ninguno': 0,
      'Primaria incompleta': 1,
      'Primaria completa': 2,
      'Secundaria (Bachillerato) incompleta': 3,
      'Secundaria (Bachillerato) completa': 4,
      'Técnica o tecnológica incompleta': 5,
      'Técnica o tecnológica completa': 6,
      'Educación profesional incompleta': 7,
      'Educación profesional completa': 8,
      'Postgrado': 9,
      'No sabe': -1,
      'No aplica': -2
  }

  for col in ['FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE']:
    if col in df.columns:
        df[col] = df[col].map(educacion_orden)

  # Codificación ordinal para estrato
  estrato_map = {
      'Sin Estrato': 0,
      'Estrato 1': 1,
      'Estrato 2': 2,
      'Estrato 3': 3,
      'Estrato 4': 4,
      'Estrato 5': 5,
      'Estrato 6': 6
  }
  if 'FAMI_ESTRATOVIVIENDA' in df.columns:
    df['FAMI_ESTRATOVIVIENDA'] = df['FAMI_ESTRATOVIVIENDA'].map(estrato_map)

  # Codificación ordinal para horas de trabajo
  horas_map = {
      '0': 0,
      'Menos de 10 horas': 1,
      'Entre 11 y 20 horas': 2,
      'Entre 21 y 30 horas': 3,
      'Más de 30 horas': 4
  }
  if 'ESTU_HORASSEMANATRABAJA' in df.columns:
    df['ESTU_HORASSEMANATRABAJA'] = df['ESTU_HORASSEMANATRABAJA'].map(horas_map)

  # Codificación ordinal para matrícula
  matricula_map = {
      'No pagó matrícula': 0,
      'Menos de 500 mil': 1,
      'Entre 500 mil y menos de 1 millón': 2,
      'Entre 1 millón y menos de 2.5 millones': 3,
      'Entre 2.5 millones y menos de 4 millones': 4,
      'Entre 4 millones y menos de 5.5 millones': 5,
      'Entre 5.5 millones y menos de 7 millones': 6,
      'Más de 7 millones': 7
  }
  if 'ESTU_VALORMATRICULAUNIVERSIDAD' in df.columns:
    df['ESTU_VALORMATRICULAUNIVERSIDAD'] = df['ESTU_VALORMATRICULAUNIVERSIDAD'].map(matricula_map)

  # Codificación binaria para Si/No
  bin_cols = [col for col in df.columns if df[col].nunique() == 2 and df[col].dtype == 'object']
  for col in bin_cols:
    df[col] = df[col].map({'Si': 1, 'No': 0, 'S': 1, 'N': 0})

  # Codificación ordinal para el resto de categóricas usando OrdinalEncoder
  categ_cols = df.select_dtypes(include='object').columns.tolist()
  if 'RENDIMIENTO_GLOBAL' in categ_cols:
    categ_cols.remove('RENDIMIENTO_GLOBAL')
  if es_entrenamiento:
    encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    df[categ_cols] = encoder.fit_transform(df[categ_cols])
  else:
    df[categ_cols] = encoder.transform(df[categ_cols])

  # Codificar la variable objetivo si es entrenamiento
  if es_entrenamiento and 'RENDIMIENTO_GLOBAL' in df.columns:
    mapeo_target = {'bajo': 0, 'medio-bajo': 1, 'medio-alto': 2, 'alto': 3}
    df['RENDIMIENTO_GLOBAL'] = df['RENDIMIENTO_GLOBAL'].map(mapeo_target)

  return df, mapeo_target, encoder

In [23]:
dtr_proc, mapeo_target, encoder = preprocesar_datos(dtr, es_entrenamiento=True)

/tmp/ipython-input-22-2469281481.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipython-input-22-2469281481.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

## Separación

In [24]:
X = dtr_proc.drop('RENDIMIENTO_GLOBAL', axis=1)
y = dtr_proc['RENDIMIENTO_GLOBAL']

## Carga y Preprocesado del archivo test

In [25]:
dts = pd.read_csv('test.csv')

In [26]:
dts.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,FAMI_TIENEAUTOMOVIL,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,coef_1,coef_2,coef_3,coef_4
0,550236,20183,TRABAJO SOCIAL,BOLIVAR,Menos de 500 mil,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica completa,Si,No,N,Si,Si,Si,Primaria completa,0.328,0.219,0.317,0.247
1,98545,20203,ADMINISTRACION COMERCIAL Y DE MERCADEO,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Si,No,N,No,Si,Si,Técnica o tecnológica completa,0.227,0.283,0.296,0.324
2,499179,20212,INGENIERIA MECATRONICA,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,0,Estrato 3,Si,Secundaria (Bachillerato) incompleta,Si,No,N,No,Si,Si,Secundaria (Bachillerato) completa,0.285,0.228,0.294,0.247
3,782980,20195,CONTADURIA PUBLICA,SUCRE,Entre 1 millón y menos de 2.5 millones,Entre 21 y 30 horas,Estrato 1,No,Primaria incompleta,Si,No,N,No,No,No,Primaria incompleta,0.160,0.408,0.217,0.294
4,785185,20212,ADMINISTRACION DE EMPRESAS,ATLANTICO,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Si,No,N,No,Si,Si,Secundaria (Bachillerato) completa,0.209,0.283,0.306,0.286

Se utiliza la misma función con los parámetros que guardamos cuando la aplicamos en el archivo train

In [27]:
dts_proc, _, _ = preprocesar_datos(dts, es_entrenamiento=False, mapeo_target=mapeo_target, encoder=encoder)

/tmp/ipython-input-22-2469281481.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipython-input-22-2469281481.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [28]:
X_test = dts_proc.drop(columns=['ID'])
X_test = X_test.reindex(columns=X.columns, fill_value=0)

In [29]:
X_test.head()

,ID,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_EDUCACIONMADRE,coef_1,coef_2,coef_3,coef_4
0,0,943.0,5.0,1,1,3,1,6.0,1,1,2.0,0.328,0.219,0.317,0.247
1,0,12.0,1.0,4,3,2,1,4.0,0,1,6.0,0.227,0.283,0.296,0.324
2,0,456.0,4.0,3,0,3,1,3.0,0,1,4.0,0.285,0.228,0.294,0.247
3,0,229.0,27.0,3,3,1,0,1.0,0,0,1.0,0.160,0.408,0.217,0.294
4,0,14.0,3.0,4,2,2,1,4.0,0,1,4.0,0.209,0.283,0.306,0.286

# Solución final

## Optuna y validación cruzada

Se utiliza una función de optimización con optuna para identificar los parámetros más adecuados para el modelo escogido

In [31]:
# Submuestreo (10%)
X_sample, _, y_sample, _ = train_test_split(X, y, train_size=0.1, stratify=y, random_state=42)

def objective(trial):
  params = {
      'n_estimators': trial.suggest_int('n_estimators', 50, 200),
      'max_depth': trial.suggest_int('max_depth', 5, 30),
      'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
      'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
      'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
      'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
      'random_state': 42,
      'n_jobs': -1
  }

  pipeline = Pipeline([
      ("imputer", SimpleImputer(strategy="most_frequent")),
      ("clf", RandomForestClassifier(**params))
  ])

  cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
  scores = cross_val_score(pipeline, X_sample, y_sample, cv=cv, scoring='accuracy', n_jobs=-1)

  return scores.mean()

# Ejecutar la optimización
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30)

print("Mejores parámetros encontrados:")
print(study.best_params)

[I 2025-07-04 03:20:01,060] A new study created in memory with name: no-name-2beefc61-6814-415d-a4ef-0bb1aa84764e
[I 2025-07-04 03:20:38,681] Trial 0 finished with value: 0.38987726502973347 and parameters: {'n_estimators': 148, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.38987726502973347.
[I 2025-07-04 03:21:27,979] Trial 1 finished with value: 0.39373283505087014 and parameters: {'n_estimators': 186, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 1 with value: 0.39373283505087014.
[I 2025-07-04 03:21:56,850] Trial 2 finished with value: 0.39124906656615116 and parameters: {'n_estimators': 137, 'max_depth': 21, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 1 with value: 0.39373283505087014.
[I 2025-07-04 03:22:21,818] Trial 3 finished with value: 0.3957978005278649 and parameters: {'n_estimators': 150, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 3 with value: 0.3957978005278649.
[I 2025-07-04 03:22:45,219] Trial 4 finished with value: 0.39591332441066324 and parameters: {'n_estimators': 122, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:23:17,716] Trial 5 finished with value: 0.39175447213675424 and parameters: {'n_estimators': 109, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
[I 2025-07-04 03:24:15,922] Trial 6 finished with value: 0.38888084260801753 and parameters: {'n_estimators': 176, 'max_depth': 21, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:26:52,121] Trial 7 finished with value: 0.3297761323436797 and parameters: {'n_estimators': 110, 'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:27:16,064] Trial 8 finished with value: 0.38648376739372603 and parameters: {'n_estimators': 95, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
/usr/local/lib/python3.11/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
[I 2025-07-04 03:30:26,044] Trial 9 finished with value: 0.33358840421122343 and parameters: {'n_estimators': 139, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:30:31,928] Trial 10 finished with value: 0.37839710498138107 and parameters: {'n_estimators': 51, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:30:51,815] Trial 11 finished with value: 0.3937761200675078 and parameters: {'n_estimators': 161, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:31:06,094] Trial 12 finished with value: 0.3940794235896363 and parameters: {'n_estimators': 80, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:31:26,645] Trial 13 finished with value: 0.39419492057295474 and parameters: {'n_estimators': 122, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:33:05,600] Trial 14 finished with value: 0.3730107737621892 and parameters: {'n_estimators': 164, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:33:18,208] Trial 15 finished with value: 0.3926642331920771 and parameters: {'n_estimators': 73, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:33:52,710] Trial 16 finished with value: 0.3951768610653547 and parameters: {'n_estimators': 196, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:34:13,047] Trial 17 finished with value: 0.39250536861697327 and parameters: {'n_estimators': 124, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:34:24,529] Trial 18 finished with value: 0.37992777547188766 and parameters: {'n_estimators': 154, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:35:48,451] Trial 19 finished with value: 0.3693718671661442 and parameters: {'n_estimators': 103, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': False}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:36:13,641] Trial 20 finished with value: 0.39571113916147177 and parameters: {'n_estimators': 138, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:36:37,603] Trial 21 finished with value: 0.3952346405226943 and parameters: {'n_estimators': 133, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:37:09,854] Trial 22 finished with value: 0.395306835599004 and parameters: {'n_estimators': 173, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 4 with value: 0.39591332441066324.
[I 2025-07-04 03:37:32,176] Trial 23 finished with value: 0.39672198345785076 and parameters: {'n_estimators': 146, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 23 with value: 0.39672198345785076.
[I 2025-07-04 03:37:43,552] Trial 24 finished with value: 0.38761006676028037 and parameters: {'n_estimators': 119, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 23 with value: 0.39672198345785076.
[I 2025-07-04 03:38:03,244] Trial 25 finished with value: 0.3957400210705253 and parameters: {'n_estimators': 149, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 23 with value: 0.39672198345785076.
[I 2025-07-04 03:38:38,207] Trial 26 finished with value: 0.3963754280742575 and parameters: {'n_estimators': 169, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 23 with value: 0.39672198345785076.
[I 2025-07-04 03:39:10,369] Trial 27 finished with value: 0.3969241662047651 and parameters: {'n_estimators': 174, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 27 with value: 0.3969241662047651.
[I 2025-07-04 03:39:38,003] Trial 28 finished with value: 0.3904981544466996 and parameters: {'n_estimators': 195, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 27 with value: 0.3969241662047651.
[I 2025-07-04 03:40:30,187] Trial 29 finished with value: 0.39371838314888064 and parameters: {'n_estimators': 178, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 27 with value: 0.3969241662047651.

Mejores parámetros encontrados:
{'n_estimators': 174, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}

## Entrenar modelo y realizar predicciones

In [32]:
# Entrenar pipeline con todos los datos
best_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("clf", RandomForestClassifier(
        **study.best_params,
        random_state=42,
        n_jobs=-1
    ))
])

best_pipeline.fit(X, y)

# Predecir
y_preds = best_pipeline.predict(X_test)

# Revertir codificación
reverse_map = {v: k for k, v in mapeo_target.items()}
y_preds_labels = pd.Series(y_preds).map(reverse_map)

## Generar archivo de solución para Kaggle

In [33]:
submission = pd.DataFrame({
    'ID': dts['ID'],
    'RENDIMIENTO_GLOBAL': y_preds_labels
})
submission.head()

       ID RENDIMIENTO_GLOBAL
0  550236               alto
1   98545         medio-bajo
2  499179               alto
3  782980               bajo
4  785185               bajo

In [34]:
submission.to_csv('submission10.csv', index=False)

In [36]:
!head submission10.csv

ID,RENDIMIENTO_GLOBAL
550236,alto
98545,medio-bajo
499179,alto
782980,bajo
785185,bajo
58495,bajo
705444,alto
557548,alto
519909,medio-bajo